_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 55
            "2":
                - 55
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
                - 61
            "4": 3.12.7
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": darwin-x86_64
benchmarks:
    value:
        - MathVista
        - MathVision
        - MathVerse
        - DynaMath
        - WeMath
        - LogicVista
